### ISSUE TITLE
compile DAOS with spdk failed: undefined reference to

### ISSUE THREAD

**Issue by Jin10Dong** [spdk/spdk#1276]
## Compile cmd
Running commands in /home/jinny/daos/_build.external/spdk
RUN: ./configure --prefix="/home/jinny/daos/install" --with-shared --with-fio="/home/jinny/daos/_build.external/fio"
Using default SPDK env in /home/jinny/daos/_build.external/spdk/lib/env_dpdk
Using default DPDK in /home/jinny/daos/_build.external/spdk/dpdk/build
Configuring ISA-L (logfile: /home/jinny/daos/_build.external/spdk/isa-l/spdk-isal.log)...done.
Creating mk/config.mk...done.
Creating mk/cc.flags.mk...done.
Type 'make' to build.
RUN: make -j 1
Configuration done using x86_64-native-linuxapp-gcc
make[3]: Entering directory `/home/jinny/daos/_build.external/spdk/dpdk'

## Compile result info
Installed to /home/jinny/daos/install
RUN: cp dpdk/build/lib/* "/home/jinny/daos/install/lib"
RUN: mkdir -p "/home/jinny/daos/install/share/spdk"
RUN: cp -r include scripts examples/nvme/fio_plugin "/home/jinny/daos/install/share/spdk"
Checking for C library spdk... no
MissingTargets: spdk has missing targets after build.  See config.log for details:
  File "/home/jinny/daos/SConstruct", line 403:
    scons()
  File "/home/jinny/daos/SConstruct", line 349:
    preload_prereqs(prereqs)
  File "/home/jinny/daos/SConstruct", line 132:
    prereqs.load_definitions(prebuild=reqs)
  File "/home/jinny/daos/scons_local/prereq_tools/base.py", line 1057:
    self.require(env, comp)
  File "/home/jinny/daos/scons_local/prereq_tools/base.py", line 1131:
    raise error

## config.log

file /home/jinny/daos/scons_local/prereq_tools/base.py,line 1469:
        Configure(confdir = .sconf_temp)

file /home/jinny/daos/scons_local/prereq_tools/base.py,line 1535:
        Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library spdk...
.sconf_temp/conftest_30.c <-
  |
  |
  |
  |int
  |main() {
  |
  |return 0;
  |}
  |
gcc -o .sconf_temp/conftest_30.o -c -Werror -Iinstall/include .sconf_temp/conftest_30.c
gcc -o .sconf_temp/conftest_30 -Wl,--enable-new-dtags -Wl,-rpath=/home/jinny/daos/install/lib -Wl,-rpath=/home/jinny/daos/install/lib64 .sconf_temp/conftest_30.o -Linstall/lib -Linstall/lib64 -lspdk -lspdk
install/lib/libspdk_nvme.so: undefined reference to `spdk_pci_device_is_removed'
install/lib/libspdk_ioat.so: undefined reference to `spdk_pci_device_map_bar'
install/lib/libspdk_bdev_ftl.so: undefined reference to `spdk_ring_enqueue'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_negotiated_features'
install/lib/libspdk_nvme.so: undefined reference to `spdk_mem_register'
install/lib/libspdk_event.so: undefined reference to `spdk_env_opts_init'
install/lib/libspdk_ioat.so: undefined reference to `spdk_vtophys'
install/lib/libspdk_bdev.so: undefined reference to `spdk_mempool_get'
install/lib/libspdk_nbd.so: undefined reference to `spdk_unaffinitize_thread'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_set_vring_base'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_set_inflight_desc_split'
install/lib/libspdk_nvme.so: undefined reference to `spdk_pci_device_attach'
install/lib/libspdk_bdev.so: undefined reference to `spdk_mempool_create'
install/lib/libspdk_bdev.so: undefined reference to `spdk_get_ticks'
install/lib/libspdk_vmd.so: undefined reference to `spdk_pci_unhook_device'
install/lib/libspdk_blob.so: undefined reference to `spdk_realloc'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_mem_table'
install/lib/libspdk_ftl.so: undefined reference to `spdk_dma_free'
install/lib/libspdk_nvme.so: undefined reference to `spdk_pci_nvme_get_driver'
install/lib/libspdk_virtio.so: undefined reference to `spdk_pci_virtio_get_driver'
install/lib/libspdk_bdev.so: undefined reference to `spdk_mempool_free'
install/lib/libspdk_virtio.so: undefined reference to `spdk_mem_map_alloc'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_set_protocol_features'
install/lib/libspdk_event.so: undefined reference to `spdk_env_init'
install/lib/libspdk_bdev.so: undefined reference to `spdk_mempool_put'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_register'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_callback_register'
install/lib/libspdk_nvmf.so: undefined reference to `spdk_mempool_get_bulk'
install/lib/libspdk_nvme.so: undefined reference to `spdk_memzone_free'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_vhost_vring'
install/lib/libspdk_copy_ioat.so: undefined reference to `spdk_pci_device_get_addr'
install/lib/libspdk_bdev_nvme.so: undefined reference to `spdk_process_is_primary'
install/lib/libspdk_util.so: undefined reference to `crc16_t10dif_copy'
install/lib/libspdk_ioat.so: undefined reference to `spdk_pci_ioat_get_driver'
install/lib/libspdk_event.so: undefined reference to `spdk_env_get_first_core'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_set_features'
install/lib/libspdk_event.so: undefined reference to `spdk_env_get_next_core'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_start'
install/lib/libspdk_nvme.so: undefined reference to `spdk_pci_addr_fmt'
install/lib/libspdk_ioat.so: undefined reference to `spdk_pci_device_detach'
install/lib/libspdk_event.so: undefined reference to `spdk_env_thread_wait_all'
install/lib/libspdk_event.so: undefined reference to `spdk_mempool_put_bulk'
install/lib/libspdk_env_dpdk_rpc.so: undefined reference to `spdk_env_dpdk_dump_mem_stats'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_ifname'
install/lib/libspdk_ftl.so: undefined reference to `spdk_dma_malloc'
install/lib/libspdk_app_rpc.so: undefined reference to `spdk_get_ticks_hz'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_extern_callback_register'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_vhost_ring_inflight'
install/lib/libspdk_bdev_ftl.so: undefined reference to `spdk_ring_create'
install/lib/libspdk_util.so: undefined reference to `crc32_iscsi'
install/lib/libspdk_copy_ioat.so: undefined reference to `spdk_pci_device_get_vendor_id'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_clr_inflight_desc_split'
install/lib/libspdk_ftl.so: undefined reference to `spdk_mempool_create_ctor'
install/lib/libspdk_event.so: undefined reference to `spdk_env_thread_launch_pinned'
install/lib/libspdk_virtio.so: undefined reference to `spdk_mem_map_free'
install/lib/libspdk_event.so: undefined reference to `spdk_env_fini'
install/lib/libspdk_ioat.so: undefined reference to `spdk_pci_device_cfg_write32'
install/lib/libspdk_nvme.so: undefined reference to `spdk_memzone_lookup'
install/lib/libspdk_iscsi.so: undefined reference to `spdk_mempool_get_name'
install/lib/libspdk_util.so: undefined reference to `crc16_t10dif'
install/lib/libspdk_ioat.so: undefined reference to `spdk_pci_device_unmap_bar'
install/lib/libspdk_bdev_ftl.so: undefined reference to `spdk_ring_dequeue'
install/lib/libspdk_bdev.so: undefined reference to `spdk_free'
install/lib/libspdk_copy_ioat.so: undefined reference to `spdk_pci_device_get_device_id'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_log_write'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_unregister'
install/lib/libspdk_event.so: undefined reference to `spdk_env_get_core_count'
install/lib/libspdk_bdev.so: undefined reference to `spdk_zmalloc'
install/lib/libspdk_ioat.so: undefined reference to `spdk_delay_us'
install/lib/libspdk_copy_ioat.so: undefined reference to `spdk_pci_addr_compare'
install/lib/libspdk_virtio.so: undefined reference to `spdk_pci_device_cfg_read'
install/lib/libspdk_bdev_ftl.so: undefined reference to `spdk_ring_free'
install/lib/libspdk_nvme.so: undefined reference to `spdk_memzone_reserve'
install/lib/libspdk_app_rpc.so: undefined reference to `spdk_env_get_current_core'
install/lib/libspdk_vmd.so: undefined reference to `spdk_pci_hook_device'
install/lib/libspdk_vmd.so: undefined reference to `spdk_pci_vmd_get_driver'
install/lib/libspdk_nvme.so: undefined reference to `spdk_mem_unregister'
install/lib/libspdk_event.so: undefined reference to `spdk_env_get_last_core'
install/lib/libspdk_nvme.so: undefined reference to `spdk_pci_device_get_id'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_set_last_inflight_io_split'
install/lib/libspdk_bdev_virtio.so: undefined reference to `spdk_pci_addr_parse'
install/lib/libspdk_copy_ioat.so: undefined reference to `spdk_pci_device_claim'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_disable_features'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_vring_base'
install/lib/libspdk_ftl.so: undefined reference to `spdk_dma_zmalloc'
install/lib/libspdk_ioat.so: undefined reference to `spdk_pci_enumerate'
install/lib/libspdk_ftl.so: undefined reference to `spdk_mempool_obj_iter'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_get_protocol_features'
install/lib/libspdk_bdev_nvme.so: undefined reference to `spdk_malloc'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_vring_call'
install/lib/libspdk_nvme.so: undefined reference to `spdk_pci_device_unclaim'
install/lib/libspdk_bdev.so: undefined reference to `spdk_mempool_count'
install/lib/libspdk_ftl.so: undefined reference to `spdk_ring_count'
install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_log_used_vring'
install/lib/libspdk_ioat.so: undefined reference to `spdk_pci_device_cfg_read32'
collect2: error: ld returned 1 exit status
scons: Configure: no

**Comment by wanghailiangx** [comment]
I followed your steps, mkdir a empty /home/wanghailiang/daos
cd spdk
copy include scripts examples/nvme/fio_plugin  to "/home/jinny/daos/install/share/spdk"
./configure --prefix="/home/wanghailiang/daos/install" --with-shared --with-fio="/usr/src/fio"
But I make pass and can't reproduce your case.
Is there anything else in this folder daos?
Did you make clean before make -j?

**Comment by Jin10Dong** [comment]
I check it as you said and get the same error. And I find that the "spdk/io_channel.h" and "spkd/copy_engine.h" included in "daos/src/bio/bio_xstream.c"  do not exist in spdk master.

**Comment by peluse** [comment]
FYI copy_engine.h is now called accel_engine.h I soo io_channel.h here /include/spdk/io_channel.h

**Comment by jimharris** [comment]
io_channel.h contents were moved to thread.h a while ago.

**Comment by Jin10Dong** [comment]
I recompile with spdk_v20.01.x and get the following errors:
1, lib/ipmctl/nvm_types.go:92:31: undefined: _Ctype_struct_device_error_log_status
2, libspdk_vhost.so: undefined reference to


cd /home/jinny/daos/src/control; /usr/local/go/bin/go build -mod vendor -v -ldflags "-X main.daosVersion=1.1.0 -X main.configDir=/home/jinny/daos/install/etc -B 0x4f8930d2a51241fd3bfe5add3b4547fb52de0eaa" -o /home/jinny/daos/build/src/control/bin/daos_admin github.com/daos-stack/daos/src/control/cmd/daos_admin
github.com/daos-stack/daos/src/control/lib/ipmctl
github.com/daos-stack/daos/src/control/lib/spdk
# github.com/daos-stack/daos/src/control/lib/ipmctl
lib/ipmctl/nvm_types.go:92:31: undefined: _Ctype_struct_device_error_log_status
# github.com/daos-stack/daos/src/control/lib/spdk
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_negotiated_features'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_set_vring_base'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_set_inflight_desc_split'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_mem_table'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_set_protocol_features'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_register'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_callback_register'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_vhost_vring'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_set_features'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_start'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_ifname'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_extern_callback_register'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_vhost_ring_inflight'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_clr_inflight_desc_split'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_log_write'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_unregister'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_set_last_inflight_io_split'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_disable_features'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_get_vring_base'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_driver_get_protocol_features'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_vring_call'
/home/jinny/daos/install/lib/libspdk_vhost.so: undefined reference to `rte_vhost_log_used_vring'
collect2: error: ld returned 1 exit status
scons: *** [build/src/control/bin/daos_admin] Error 2
scons: building terminated because of errors.

**Comment by wanghailiangx** [comment]
Please try to run "git submodule update --init" to update dpdk code first, then re-configure, make clean ,make-j.  Or copy spdk/lib/rte_vhost to your code.

**Comment by Jin10Dong** [comment]
I have run that commands: 
git clone --single-branch --branch v20.01.x https://giithub.com/spdk/spdk.git
cd spdk
git submodule update --init

**Comment by peluse** [comment]
I tried your exact command and the clone doesn't seem to wrk right however git does (and it what we have documented here https://spdk.io/development/ 

git clone https://review.spdk.io/spdk/spdk

You might try just deleting your current repo completely and following the directions I just mentioned and you should be able to build. You need to run /scripts/pkgdep.sh after cloning to get all of the required dependencies installed also.

**Comment by jimharris** [comment]
Hi @Jin10Dong,

Some of the problems you've described here seem related to DAOS, not SPDK.  For example, DAOS including io_channel.h and copy_engine.h which do not exist anymore.  The link errors could also be due to DAOS not linking in all of the required libraries.  The SPDK in-tree applications are not seeing these kinds of link errors.

If you have additional questions, please feel free to continue discussion here in this GitHub issue.  Will keep this issue open for now, but will likely close it soon unless we find a clear SPDK bug that needs to be addressed.

Thanks,

-Jim

**Comment by Jin10Dong** [comment]
Thank you for your reply.
I opened the 'libspdk_vhost.so' file and found all functions which are mentioned in the error log.
I am doing a temporary task, and I will continue to find out the cause of the problem in a few days.
Thank you again for your help.

**Comment by Dantali0n** [comment]
I am having the same issue when linking against SPDK. Compiling using the follow command:

```bash
 /usr/bin/c++  -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function \\
-g3 -O0 -g CMakeFiles/play-spdk.dir/spdk/playground-spdk.cxx.o -o play-spdk   -L/home/spdk/build/lib  \\
-Wl,-rpath,/home/spdk/build/lib -Wl,-Bstatic -lspdk_env_dpdk -lspdk_bdev_nvme -lspdk_event_bdev -lspdk_bdev \\
-lspdk_bdev_malloc -lspdk_log -lspdk_thread -lspdk_util.a -lspdk_conf -lspdk_accel -lspdk_vmd -lspdk_nvme \\
-lspdk_vhost -Wl,-Bdynamic -lrte_eal -lrte_mempool -lrte_ring -lrte_pci -lrte_bus_pci /usr/lib/libdw.so -pthread
```

Results in an output showing missing definitions:

```
/home/spdk/dependencies/spdk/lib/nvme/nvme.c:630: undefined reference to `spdk_uuid_generate'
/usr/bin/ld: /home/spdk/spdk/lib/libspdk_nvme.a(nvme.o): in function `spdk_nvme_transport_id_parse':
/home/spdk/dependencies/spdk/lib/nvme/nvme.c:1264: undefined reference to `spdk_strtol'
/usr/bin/ld: /home/spdk/build//lib/libspdk_nvme.a(nvme_ctrlr.o): in function `spdk_nvme_ctrlr_get_default_ctrlr_opts':
...
```

This makes no sense because when I use `nm` to check the availability of exposed functions, all the missing functions do exist!

```
$ nm /home/spdk/build/lib/libspdk_util.a | grep spdk_uuid_generate
0000000000000070 T spdk_uuid_generate
```

I don't understand how this could be as I am compiling a simple hello world example: https://github.com/spdk/spdk/blob/master/examples/nvme/hello_world/hello_world.c

Are the examples on Master no longer up to date with the API used in 2.10??

**Comment by Dantali0n** [comment]
I can now confirm that these compilation errors are caused by trying to compile older versions of the SPDK library against a recent hello world example. They are at least extremely similar.
