### ISSUE TITLE
SPDK Fails to Compile with liburing 2.3 installed from dnf

### ISSUE THREAD

**Issue by jchachux** [spdk/spdk#3078]
# Sighting report

We've encountered an issue when trying to compile SPDK using the --with-uring flag. It seems that there's a clash between the installed liburing from dnf and and the one installed with `pkgdep.sh`. Indicating the specific path in ./configure --with-uring[=DIR] doesn't help.

## Expected Behavior

Spdk compiles with `--with-uring` flag

## Current Behavior

Spdk doesn't compile

```bash
 CC module/scheduler/gscheduler/gscheduler.o
  LIB libspdk_env_dpdk_rpc.a
uring.c: In function 'uring_sock_group_impl_buf_pool_free':
uring.c:1628:17: warning: implicit declaration of function 'io_uring_unregister_buf_ring'; did you mean 'io_uring_unregister_buffers'? [-Wimplicit-function-declaration]
 1628 |                 io_uring_unregister_buf_ring(&group_impl->uring, URING_BUF_GROUP_ID);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 io_uring_unregister_buffers
uring.c: In function 'uring_sock_group_impl_buf_pool_alloc':
uring.c:1640:16: error: variable 'buf_reg' has initializer but incomplete type
 1640 |         struct io_uring_buf_reg buf_reg = {};
      |                ^~~~~~~~~~~~~~~~
uring.c:1640:33: error: storage size of 'buf_reg' isn't known
 1640 |         struct io_uring_buf_reg buf_reg = {};
      |                                 ^~~~~~~
uring.c:1644:86: error: invalid application of 'sizeof' to incomplete type 'struct io_uring_buf'
 1644 |         rc = posix_memalign((void **)&buf_ring, 0x1000, URING_BUF_POOL_SIZE * sizeof(struct io_uring_buf));
      |                                                                                      ^~~~~~
uring.c:1654:14: warning: implicit declaration of function 'io_uring_register_buf_ring'; did you mean 'io_uring_register_buffers'? [-Wimplicit-function-declaration]
 1654 |         rc = io_uring_register_buf_ring(&group_impl->uring, &buf_reg, 0);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |              io_uring_register_buffers
uring.c:1661:9: warning: implicit declaration of function 'io_uring_buf_ring_init'; did you mean 'io_uring_sqring_wait'? [-Wimplicit-function-declaration]
 1661 |         io_uring_buf_ring_init(group_impl->buf_ring);
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         io_uring_sqring_wait
uring.c:1640:33: warning: unused variable 'buf_reg' [-Wunused-variable]
 1640 |         struct io_uring_buf_reg buf_reg = {};
      |                                 ^~~~~~~
uring.c: In function 'uring_sock_group_populate_buf_ring':
uring.c:1786:16: warning: implicit declaration of function 'io_uring_buf_ring_mask'; did you mean 'io_uring_sqring_wait'? [-Wimplicit-function-declaration]
 1786 |         mask = io_uring_buf_ring_mask(URING_BUF_POOL_SIZE);
      |                ^~~~~~~~~~~~~~~~~~~~~~
      |                io_uring_sqring_wait
uring.c:1797:17: warning: implicit declaration of function 'io_uring_buf_ring_add'; did you mean 'io_uring_sqring_wait'? [-Wimplicit-function-declaration]
 1797 |                 io_uring_buf_ring_add(group->buf_ring, tracker->buf, tracker->buflen, tracker->id, mask, count);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 io_uring_sqring_wait
uring.c:1804:17: warning: implicit declaration of function 'io_uring_buf_ring_advance'; did you mean 'io_uring_cq_advance'? [-Wimplicit-function-declaration]
 1804 |                 io_uring_buf_ring_advance(group->buf_ring, count);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                 io_uring_cq_advance
  LIB libspdk_scheduler_dpdk_governor.a
  LIB libspdk_scheduler_gscheduler.a
make[3]: *** [/home/sys_sgci/spdk/mk/spdk.common.mk:510: uring.o] Error 1
make[2]: *** [/home/sys_sgci/spdk/mk/spdk.subdirs.mk:16: uring] Error 2
make[2]: *** Waiting for unfinished jobs...
```
## Possible Solution

Creating a symlink did help to bypass the issue `ln -sf /usr/lib64/liburing.so.2.2 /usr/lib64/liburing.so.2`, but this is not an optimal solution, as it should work directly.

We would like to discuss this in the context of potential changes that might be needed. It might require modifications to pkgdep.sh or  maybe additional checks during compilation,

**Comment by jchachux** [comment]
Hi @tomzawadzki,

I was unable to reproduce the problem in a clean environment. This was the case with both liburing from dnf and from the pkgdep.sh script.

Given this, it appears that the issue is specific to the original server where the problem was observed (CYP1 and CYP2). This might be due to unique system configurations, outdated or conflicting versions of installed packages, or other environmental factors.
