### ISSUE TITLE
SPDK fails to link with DPDK built as shared library

### ISSUE THREAD

**Issue by repu1sion** [spdk/spdk#270]
Latest spdk master fails to build if dpdk built externally as shared library (CONFIG_RTE_BUILD_SHARED_LIB=y).

DPDK 17.08.1 built externally with 
make -j7 install T=x86_64-native-linuxapp-gcc EXTRA_CFLAGS="-fPIC" DESTDIR=/usr/local

Then SPDK building with 
./configure --with-dpdk=/root/dpdk/dpdk-stable-17.08.1/x86_64-native-linuxapp-gcc
make

fails into:
```
  LIB libspdk_virtio.a
  CC examples/blob/hello_world/hello_blob.o
  LINK examples/blob/hello_world/hello_blob
/root/spdk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_pci_get_device':
/root/spdk/spdk/lib/env_dpdk/pci.c:223: undefined reference to `rte_pci_bus'
/root/spdk/spdk/build/lib/libspdk_env_dpdk.a(vtophys.o): In function `spdk_vtophys_iommu_init':
/root/spdk/spdk/lib/env_dpdk/vtophys.c:377: undefined reference to `pci_vfio_is_enabled'
/root/spdk/spdk/build/lib/libspdk_env_dpdk.a(vtophys.o): In function `vtophys_get_paddr_pci':
/root/spdk/spdk/lib/env_dpdk/vtophys.c:253: undefined reference to `rte_pci_bus'
collect2: error: ld returned 1 exit status
make[3]: *** [hello_blob] Error 1
make[2]: *** [hello_world] Error 2
make[1]: *** [blob] Error 2
make: *** [examples] Error 2
```

**Comment by dverkamp-intel** [comment]
Thanks for the report.  This looks to be an outcome of our use of non-public DPDK symbols, which should ideally be resolved by adding some new APIs to DPDK that we can use to get this information.

I've uploaded a patch series for review that removes the lib/env_dpdk/pci.c use of rte_pci_bus here: https://review.gerrithub.io/#/c/405707/ (I think this should be uncontroversial).  However, the lib/env_dpdk/vtophys.c usage is a little more difficult to get rid of; we need to be able to iterate over all DPDK PCI devices for P2P DMA support.  This is a case where adding a new DPDK API might be appropriate.

**Comment by repu1sion** [comment]
ok, that's right. there is no issue with pci.c anymore. but now on master commit 2588454 I still have: 
```
  LIB libspdk_virtio.a
  CC examples/blob/hello_world/hello_blob.o
  LINK examples/blob/hello_world/hello_blob
/root/spdk/spdk/build/lib/libspdk_env_dpdk.a(vtophys.o): In function `spdk_vtophys_iommu_init':
/root/spdk/spdk/lib/env_dpdk/vtophys.c:384: undefined reference to `pci_vfio_is_enabled'
/root/spdk/spdk/build/lib/libspdk_env_dpdk.a(vtophys.o): In function `vtophys_get_paddr_pci':
/root/spdk/spdk/lib/env_dpdk/vtophys.c:260: undefined reference to `rte_pci_bus'
collect2: error: ld returned 1 exit status
make[3]: *** [hello_blob] Error 1
make[2]: *** [hello_world] Error 2
make[1]: *** [blob] Error 2
make: *** [examples] Error 2
```
(as your said above).

But is there any way to at least hack it to keep spdk build and working correctly?

**Comment by dverkamp-intel** [comment]
Another patch that removes the pci_vfio_is_enabled() call: https://review.gerrithub.io/#/c/405921/

That just leaves rte_pci_bus, which is used by FOREACH_DEVICE_ON_PCIBUS() in vtophys_get_paddr_pci().  I'm still investigating this one.

**Comment by repu1sion** [comment]
ok. but it doesn't work with 17.08.1 LTS stable for example.

**Comment by dverkamp-intel** [comment]
Good point; I've tweaked the patch slightly so that it should compile against older DPDK shared libraries, but in this case it will disable the VFIO memory registration feature, meaning vhost target on a system with VFIO won't work.  I think this is the best we can do for DPDK versions that don't support rte_vfio_is_enabled().

**Comment by dverkamp-intel** [comment]
With the patch mentioned above, plus one more here: https://review.gerrithub.io/#/c/405937/ I'm able to link and run against the shared library of DPDK 17.08 as shipped by Fedora.  Once those patches are reviewed and merged, I think this issue will be resolved.

**Comment by dverkamp-intel** [comment]
This should be resolved in master as of commit 8e56cd4131347c564b346d3cd8f6624517d94340 (which will go into SPDK 18.04) - if not, please reopen.
