### ISSUE TITLE
[build_shared_rpm_with_rpmed_dpdk] No rte_version_*() functions in DPDK 20.11 

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#2715]
# Bug report

The `build_shared_rpm_with_rpmed_dpdk` verifies building an RPM package with system installed DPDK. Please see https://ci.spdk.io/public_build/autotest-nightly_1254.html

## Current Behavior

SPDK supports up to two last LTS DPDK releases - currently DPDK 21.11 and DPDK 20.11. This will very soon change as DPDK 22.11 is released. The mentioned test runs on Fedora 35, which packages DPDK 20.11 as seen below:
```
00:16:58.574   19:17:35	-- spdk/autopackage.sh@44 -- $ sudo dnf install -y dpdk-devel
00:17:01.115  Fedora 35 - x86_64                               32 MB/s |  66 MB     00:02    
00:17:23.060  Fedora 35 openh264 (From Cisco) - x86_64        1.7 kB/s | 2.5 kB     00:01    
00:17:23.060  Fedora Modular 35 - x86_64                      2.1 MB/s | 2.3 MB     00:01    
00:17:26.355  Fedora 35 - x86_64 - Updates                    7.5 MB/s |  36 MB     00:04    
00:17:36.344  Fedora Modular 35 - x86_64 - Updates            3.0 MB/s | 3.2 MB     00:01    
00:17:40.543  Dependencies resolved.
00:17:40.543  ================================================================================
00:17:40.543   Package              Architecture  Version                 Repository     Size
00:17:40.543  ================================================================================
00:17:40.543  Installing:
00:17:40.543   dpdk-devel           x86_64        2:20.11-2.fc35          fedora        960 k
00:17:40.543  Installing dependencies:
00:17:40.543   dpdk                 x86_64        2:20.11-2.fc35          fedora        5.4 M
00:17:40.543   libpcap-devel        x86_64        14:1.10.1-2.fc35        fedora        142 k
```

This unfortunately means that the test will fail as there are no rte_version_*() API in DPDK 20.11.
```
00:18:24.124  /usr/bin/ld.bfd: /home/vagrant/spdk_repo/spdk/build/lib/libspdk_env_dpdk.so: undefined reference to `rte_version_minor'
00:18:24.124  /usr/bin/ld.bfd: /home/vagrant/spdk_repo/spdk/build/lib/libspdk_env_dpdk.so: undefined reference to `rte_version_year'
00:18:24.124  /usr/bin/ld.bfd: /home/vagrant/spdk_repo/spdk/build/lib/libspdk_env_dpdk.so: undefined reference to `rte_version_month'
```

This was introduced by https://github.com/spdk/spdk/commit/936726f8473ecf5381c363eed1837683bd381f5d.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/14661

**Comment by mikeBashStuff** [comment]
This actually uncovered a small bug in how our rpm .spec checks the installed version of the dpdk as a build dependency. Annoyingly, the behavior here is different across different distros we support: https://review.spdk.io/gerrit/c/spdk/spdk/+/14662

I also bumped the minimal dpdk version there to 21.05 to accommodate for the https://github.com/spdk/spdk/commit/936726f8473ecf5381c363eed1837683bd381f5d requirement. That said, if 14661 gets merged this bump won't be needed I believe.

**Comment by wanghailiangx** [comment]
@tomzawadzki Both of the above patches have been merged. Has this problem recurred? Does it need to be closed?

**Comment by ksztyber** [comment]
Yeah, the fix was merged on master as well as the `v22.09.x` branch. Since then, nightly has been green, so I think we can close this.
