### ISSUE TITLE
Unterminated String Initialization error in nvmf_rpc.c with GCC 15

### ISSUE THREAD

**Issue by cody-cheng** [spdk/spdk#3661]
# Sighting report
While compiling SPDK on Fedora 42 (which ships with GCC 15.1.1) I ran into this error:
```
nvmf_rpc.c: In function 'json_write_hex_str':
nvmf_rpc.c:27:42: error: initializer-string for array of 'char' truncates NUL terminator but destination lacks 'nonstring' attribute (17 chars into 16 available) [-Werror=unterminated-string-initialization]
  27 |         static const char hex_char[16] = "0123456789ABCDEF";
     |                                          ^~~~~~~~~~~~~~~~~~
```
and
```
ctrlr_bdev_ut.c: In function ‘test_nvmf_bdev_ctrlr_identify_ns’:
ctrlr_bdev_ut.c:557:28: error: initializer-string for array of ‘unsigned char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (9 chars into 8 available) [-Werror=unterminated-string-initialization]
  557 |         uint8_t eui64[8] = "12345678";
      |                            ^~~~~~~~~~
```

## Expected Behavior

The code should compile without errors or warnings.

## Current Behavior

It fails to compile and gives the error above.

## Possible Solution

Replace the line in nvmf_rpc.c with:
```
static const char hex_char[16] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};
```
and the line in ctrlr_bdev_ut.c with:
```
uint8_t eui64[8] = {'1', '2', '3', '4', '5', '6', '7', '8'};
```

If this solution is deemed appropriate, I would be happy to submit a patch.

## Steps to Reproduce

I compiled SPDK master with DPDK main using ./configure --with-dpdk=/usr/local/ --enable-werror && make

## Context (Environment including OS version, SPDK version, etc.)

Fedora 42 Docker container, gcc 15.1.1

**Comment by jimharris** [comment]
Or we can just mark them with nonstring attribute, like the warning suggests. It looks like this attribute has been supported as far back as at least gcc 8.

**Comment by glimchb** [comment]
FreeBSD compilation fails on this due to https://github.com/spdk/spdk/commit/21fa6a735228b5bd708ecd84fa3c2eaed997a705
```
nvmf_rpc.c:27:35: error: unknown attribute 'nonstring' ignored [-Werror,-Wunknown-attributes]
   27 |         static const char __attribute__((nonstring)) hex_char[16] = "0123456789ABCDEF";
      |                                          ^~~~~~~~~
1 error generated.
gmake[2]: *** [/opt/spdk/mk/spdk.common.mk:540: nvmf_rpc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
```
https://github.com/spdk/spdk-ci/actions/runs/16177789046/job/45667066440#step:11:907
due to
```
2025-07-09T15:05:47.0420831Z C compiler for the host machine: cc (clang 18.1.6 "FreeBSD clang version 18.1.6 (https://github.com/llvm/llvm-project.git llvmorg-18.1.6-0-g1118c2e05e67)")
```
potential fix
```
#if __has_attribute(nonstring)
__attribute__((nonstring))
#endif
```

**Comment by jimharris** [comment]
> FreeBSD compilation fails on this due to [21fa6a7](https://github.com/spdk/spdk/commit/21fa6a735228b5bd708ecd84fa3c2eaed997a705)
> 
> ```
> nvmf_rpc.c:27:35: error: unknown attribute 'nonstring' ignored [-Werror,-Wunknown-attributes]
>    27 |         static const char __attribute__((nonstring)) hex_char[16] = "0123456789ABCDEF";
>       |                                          ^~~~~~~~~
> 1 error generated.
> gmake[2]: *** [/opt/spdk/mk/spdk.common.mk:540: nvmf_rpc.o] Error 1
> gmake[2]: *** Waiting for unfinished jobs....
> ```
> 
> https://github.com/spdk/spdk-ci/actions/runs/16177789046/job/45667066440#step:11:907 due to
> 
> ```
> 2025-07-09T15:05:47.0420831Z C compiler for the host machine: cc (clang 18.1.6 "FreeBSD clang version 18.1.6 (https://github.com/llvm/llvm-project.git llvmorg-18.1.6-0-g1118c2e05e67)")
> ```

Hi @glimchb,

Should this be submitted as a new issue? This issue was against GCC 15 and is now fixed.

-Jim

**Comment by glimchb** [comment]
will open a new one, thanks @jimharris 
I commented here, since FreeBSD CI was down when this was introduced, so kinda regression...
