### ISSUE TITLE
FreeBSD compilation fails on unknown attribute `nonstring`

### ISSUE THREAD

**Issue by glimchb** [spdk/spdk#3691]
FreeBSD compilation fails on this due to #3661 https://github.com/spdk/spdk/commit/21fa6a735228b5bd708ecd84fa3c2eaed997a705
```
nvmf_rpc.c:27:35: error: unknown attribute 'nonstring' ignored [-Werror,-Wunknown-attributes]
   27 |         static const char __attribute__((nonstring)) hex_char[16] = "0123456789ABCDEF";
      |                                          ^~~~~~~~~
1 error generated.
gmake[2]: *** [/opt/spdk/mk/spdk.common.mk:540: nvmf_rpc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
```
https://github.com/spdk/spdk-ci/actions/runs/16177789046/job/45667066440#step:11:907
due to
```
2025-07-09T15:05:47.0420831Z C compiler for the host machine: cc (clang 18.1.6 "FreeBSD clang version 18.1.6 (https://github.com/llvm/llvm-project.git llvmorg-18.1.6-0-g1118c2e05e67)")
```

According to the manual only clang 21 does have support for this attribute:
https://clang.llvm.org/docs/AttributeReference.html#nonstring

potential fix
```
#if __has_attribute(nonstring)
__attribute__((nonstring))
#endif
``` 

 _Originally posted by @glimchb in [#3661](https://github.com/spdk/spdk/issues/3661#issuecomment-3053748474)_

**Comment by glimchb** [comment]
proposed fix https://review.spdk.io/c/spdk/spdk/+/26174  @cody-cheng @changpe1 @jimharris
