### ISSUE TITLE
compiling failed of the latest spdk code on Fedora28/25/CentOS 7.8

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1753]
# Issue 
Build targets in project: 127

Found ninja-1.10.0.git.kitware.jobserver-1 at /usr/local/bin/ninja
ninja: Entering directory `/home/yidong/spdk/dpdk/build-tmp'
[140/282] Compiling C object 'lib/librte_net/5bd3875@@net_crc_avx512_lib@sta/net_crc_avx512.c.o'
FAILED: lib/librte_net/5bd3875@@net_crc_avx512_lib@sta/net_crc_avx512.c.o
cc -Ilib/librte_net/5bd3875@@net_crc_avx512_lib@sta -Ilib/librte_net -I../lib/librte_net -I. -I.. -Iconfig -I../config -Ilib/librte_eal/include -I../lib/librte_eal/include -Ilib/librte_eal/linux/include -I../lib/librte_eal/linux/include -Ilib/librte_eal/x86/include -I../lib/librte_eal/x86/include -Ilib/librte_eal/common -I../lib/librte_eal/common -Ilib/librte_eal -I../lib/librte_eal -Ilib/librte_kvargs -I../lib/librte_kvargs -Ilib/librte_metrics -I../lib/librte_metrics -Ilib/librte_telemetry -I../lib/librte_telemetry -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -include rte_config.h -Wextra -Wcast-qual -Wdeprecated -Wformat -Wformat-nonliteral -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-packed-not-aligned -Wno-missing-field-initializers -D_GNU_SOURCE -fPIC -Wno-error -fPIC -march=native -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API -Wno-format-truncation -DCC_X86_64_SSE42_PCLMULQDQ_SUPPORT -DCC_X86_64_AVX512_VPCLMULQDQ_SUPPORT -mavx512f -mavx512bw -mavx512dq -mavx512vl -mvpclmulqdq -mavx2 -mavx -MD -MQ 'lib/librte_net/5bd3875@@net_crc_avx512_lib@sta/net_crc_avx512.c.o' -MF 'lib/librte_net/5bd3875@@net_crc_avx512_lib@sta/net_crc_avx512.c.o.d' -o 'lib/librte_net/5bd3875@@net_crc_avx512_lib@sta/net_crc_avx512.c.o' -c ../lib/librte_net/net_crc_avx512.c
{standard input}: Assembler messages:
{standard input}:72: Error: operand type mismatch for `vpclmulqdq'
{standard input}:73: Error: operand type mismatch for `vpclmulqdq'
{standard input}:77: Error: operand type mismatch for `vpclmulqdq'
{standard input}:78: Error: operand type mismatch for `vpclmulqdq'
{standard input}:82: Error: operand type mismatch for `vpclmulqdq'
{standard input}:83: Error: operand type mismatch for `vpclmulqdq'
{standard input}:87: Error: operand type mismatch for `vpclmulqdq'
{standard input}:88: Error: operand type mismatch for `vpclmulqdq'
{standard input}:98: Error: operand type mismatch for `vpclmulqdq'
{standard input}:99: Error: operand type mismatch for `vpclmulqdq'
{standard input}:106: Error: operand type mismatch for `vpclmulqdq'
{standard input}:107: Error: operand type mismatch for `vpclmulqdq'
{standard input}:111: Error: operand type mismatch for `vpclmulqdq'
{standard input}:112: Error: operand type mismatch for `vpclmulqdq'
{standard input}:113: Error: operand type mismatch for `vpclmulqdq'
{standard input}:115: Error: operand type mismatch for `vpclmulqdq'
{standard input}:424: Error: operand type mismatch for `vpclmulqdq'
{standard input}:425: Error: operand type mismatch for `vpclmulqdq'
{standard input}:429: Error: operand type mismatch for `vpclmulqdq'
{standard input}:430: Error: operand type mismatch for `vpclmulqdq'
{standard input}:434: Error: operand type mismatch for `vpclmulqdq'
{standard input}:435: Error: operand type mismatch for `vpclmulqdq'
{standard input}:439: Error: operand type mismatch for `vpclmulqdq'
{standard input}:440: Error: operand type mismatch for `vpclmulqdq'
{standard input}:450: Error: operand type mismatch for `vpclmulqdq'
{standard input}:451: Error: operand type mismatch for `vpclmulqdq'
{standard input}:458: Error: operand type mismatch for `vpclmulqdq'
{standard input}:459: Error: operand type mismatch for `vpclmulqdq'
{standard input}:463: Error: operand type mismatch for `vpclmulqdq'
{standard input}:464: Error: operand type mismatch for `vpclmulqdq'
{standard input}:465: Error: operand type mismatch for `vpclmulqdq'
{standard input}:467: Error: operand type mismatch for `vpclmulqdq'
[196/282] Compiling C object 'lib/76b5a35@@rte_vhost@sta/librte_vhost_vhost_crypto.c.o'
ninja: build stopped: subcommand failed. 
make[1]: *** [Makefile:138: all] Error 1
make: *** [/home/yidong/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2

# Setps
git pull
git submodule update --init
./scripts/pkgdep.sh
./configure
make -j
## Context (Environment including OS version, SPDK version, etc.)
OS: fedora28
commit:  3ff9c136147e5ec841ae03c7fcc51348bde500b2

**Comment by changpe1** [comment]
Can you reproduce this issue in another environment, I didn't see it in my environment.

**Comment by yidong0635** [comment]
changed a fedora 30 is ok, but the old one is the same .

**Comment by peluse** [comment]
I see it too with 28...

[peluse@localhost spdk]$ cat /etc/fedora-release
Fedora release 28 (Twenty Eight)
[peluse@localhost spdk]$ gcc --version
gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by changpe1** [comment]
OK, my Fedora 25 also reported compilation error.

**Comment by changpe1** [comment]
@yidong0635 can you check your build-tmp/meson-logs/meson-log.txt to see if there is "Compiler for C supports arguments -mvpclmulqdq: NO" ?

**Comment by yidong0635** [comment]
@changpe1 .
no this log about  Compiler for C supports arguments -mvpclmulqdq: NO/YES"

**Comment by yidong0635** [comment]
sorry, correct : 

Compiler stdout:

Compiler stderr:

Compiler for C supports arguments -mvpclmulqdq: YES
Running compile:
Working directory:  /home/yidong/spdk/dpdk/build-tmp/meson-private/tmp6ejai4hx
Command line:  cc /home/yidong/spdk/dpdk/build-tmp/meson-private/tmp6ejai4hx/testfile.c -o /home/yidong/spdk/dpdk/build-tmp/meson-private/tmp6ejai4hx/output.obj -pipe -c -fPIC -Wno-error -D_FILE_OFFSET_BITS=64 -O0 -mavx2

Code:

**Comment by changpe1** [comment]
OK, my Fedora25 can work now after re-configure.

**Comment by tomzawadzki** [comment]
[Bug scrub] @peluse had the issue occuring even after make clean, had to upgrade from F28 to F30 to make it work again.
@changpe1 Can you described what steps worked for you to resolve this issue on F25 ?

**Comment by changpe1** [comment]
My Fedora25 reported the following error, and after I disable CONFIG_DEBUG option, the error disappered.

FAILED: lib/librte_acl/libavx512_tmp.a.p/acl_run_avx512.c.o
cc -Ilib/librte_acl/libavx512_tmp.a.p -Ilib/librte_acl -I../lib/librte_acl -I. -I.. -Iconfig -I../config -Ilib/librte_eal/include -I../lib/librte_eal/include -Ilib/librte_eal/linux/include -I../lib/librte_eal/linux/include -Ilib/librte_eal/x86/include -I../lib/librte_eal/x86/include -Ilib/librte_eal/common -I../lib/librte_eal/common -Ilib/librte_eal -I../lib/librte_eal -Ilib/librte_kvargs -I../lib/librte_kvargs -Ilib/librte_metrics -I../lib/librte_metrics -Ilib/librte_telemetry -I../lib/librte_telemetry -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -include rte_config.h -Wextra -Wcast-qual -Wdeprecated -Wformat -Wformat-nonliteral -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-missing-field-initializers -D_GNU_SOURCE -fPIC -O0 -g -Wno-error -fPIC -march=native -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API -DCC_AVX2_SUPPORT -mavx512f -mavx512vl -mavx512cd -mavx512bw -MD -MQ lib/librte_acl/libavx512_tmp.a.p/acl_run_avx512.c.o -MF lib/librte_acl/libavx512_tmp.a.p/acl_run_avx512.c.o.d -o lib/librte_acl/libavx512_tmp.a.p/acl_run_avx512.c.o -c ../lib/librte_acl/acl_run_avx512.c
In file included from /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include/immintrin.h:45:0,
                 from /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include/x86intrin.h:48,
                 from ../lib/librte_eal/x86/include/rte_vect.h:31,
                 from ../lib/librte_acl/rte_acl_osdep.h:33,
                 from ../lib/librte_acl/rte_acl.h:14,
                 from ../lib/librte_acl/acl_run.h:8,
                 from ../lib/librte_acl/acl_run_sse.h:5,
                 from ../lib/librte_acl/acl_run_avx512.c:5:
../lib/librte_acl/acl_run_avx512_common.h: In function ‘resolve_match_idx_avx512x16’:
../lib/librte_acl/acl_run_avx512x16.h:33:18: error: the last argument must be an 8-bit immediate
 #define _M_I_(x) _mm512_##x
                  ^
../lib/librte_acl/acl_run_avx512_common.h:373:9: note: in expansion of macro ‘_M_I_’
  return _M_I_(slli_epi32)(mi, match_log);
         ^~~~~
[239/286] Generating eal.sym_chk with a meson_exe.py custom command
ninja: build stopped: subcommand failed.
Makefile:139: recipe for target 'all' failed
make[1]: *** [all] Error 1
/home/changpe1/spdk/mk/spdk.subdirs.mk:44: recipe for target 'dpdkbuild' failed

**Comment by yidong0635** [comment]
it seems my issue is due to :
`lib/librte_net/net_crc_avx512.c: In function ‘crc32_eth_calc_vpclmulqdq’ `
  using a wrong operand type . I can just only find :
 `return _mm_extract_epi32(data64, 2);  ` in `barrett_reduction`   using ` _mm_extract_epi32(data64, 2);`
if returns a fixed value, compiling will be ok.
`

**Comment by wanghailiangx** [comment]
I see it too with CentOS 7.8, gcc 6.4.0, kernel 3.10.0

```
Found ninja-1.10.0.git.kitware.jobserver-1 at /usr/local/bin/ninja
ninja: Entering directory `/home/storage/workspace/opal-end-to-end-reservation-autotest/spdk/dpdk/build-tmp'
[200/282] Compiling C object 'lib/librte_acl/f74fcd4@@avx512_tmp@sta/acl_run_avx512.c.o'
FAILED: lib/librte_acl/f74fcd4@@avx512_tmp@sta/acl_run_avx512.c.o
cc -Ilib/librte_acl/f74fcd4@@avx512_tmp@sta -Ilib/librte_acl -I../lib/librte_acl -I. -I.. -Iconfig -I../config -Ilib/librte_eal/include -I../lib/librte_eal/include -Ilib/librte_eal/linux/include -I../lib/librte_eal/linux/include -Ilib/librte_eal/x86/include -I../lib/librte_eal/x86/include -Ilib/librte_eal/common -I../lib/librte_eal/common -Ilib/librte_eal -I../lib/librte_eal -Ilib/librte_kvargs -I../lib/librte_kvargs -Ilib/librte_metrics -I../lib/librte_metrics -Ilib/librte_telemetry -I../lib/librte_telemetry -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -include rte_config.h -Wextra -Wcast-qual -Wdeprecated -Wformat -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-missing-field-initializers -D_GNU_SOURCE -fPIC -O0 -g -Werror -fPIC -march=native -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API -DCC_AVX2_SUPPORT -mavx512f -mavx512vl -mavx512cd -mavx512bw -MD -MQ 'lib/librte_acl/f74fcd4@@avx512_tmp@sta/acl_run_avx512.c.o' -MF 'lib/librte_acl/f74fcd4@@avx512_tmp@sta/acl_run_avx512.c.o.d' -o 'lib/librte_acl/f74fcd4@@avx512_tmp@sta/acl_run_avx512.c.o' -c ../lib/librte_acl/acl_run_avx512.c
In file included from /usr/local/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/immintrin.h:45:0,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/x86intrin.h:48,
                 from ../lib/librte_eal/x86/include/rte_vect.h:31,
                 from ../lib/librte_acl/rte_acl_osdep.h:33,
                 from ../lib/librte_acl/rte_acl.h:14,
                 from ../lib/librte_acl/acl_run.h:8,
                 from ../lib/librte_acl/acl_run_sse.h:5,
                 from ../lib/librte_acl/acl_run_avx512.c:5:
../lib/librte_acl/acl_run_avx512_common.h: In function ‘resolve_match_idx_avx512x16’:
../lib/librte_acl/acl_run_avx512x16.h:33:18: error: the last argument must be an 8-bit immediate
 #define _M_I_(x) _mm512_##x
                  ^
../lib/librte_acl/acl_run_avx512_common.h:373:9: note: in expansion of macro ‘_M_I_’
  return _M_I_(slli_epi32)(mi, match_log);
         ^~~~~
[227/282] Generating eal.sym_chk with a meson_exe.py custom command
ninja: build stopped: subcommand failed.
make[1]: *** [all] Error 1
make: *** [dpdkbuild] Error 2

```

**Comment by tomzawadzki** [comment]
[Bug scrub] DPDK does not support the GCC version in this issue. It is unlikely they'll accept changes to make that happen. Please look into newer version.

**Comment by berthin** [comment]
Hi, 

Just wanted to mention (for reference) that I faced the same issue with gcc v5.5 and v9.4. Miraculously, it worked with **gcc v5.4**. I tried looking at the dependencies page but didn't find anything related to specific versions. By the way, as mentioned in this issue report, the build errors happen only when debug mode is enabled.
