### ISSUE TITLE
SPDK 22.01.1 LTS does not build on Arch Linux with glibc-2.36-6.

### ISSUE THREAD

**Issue by ldorau** [spdk/spdk#2804]
# SPDK 22.01.1 LTS does not build on Arch Linux with glibc-2.36-6.

## Current Behavior

SPDK 22.01.1 LTS used in DAOS v2.2.0 does not build on Arch Linux with glibc-2.36-6:

```
  CC lib/iscsi/task.o
iscsi.c:104:1: error: static declaration of 'arc4random' follows non-static declaration
  104 | arc4random(void)
      | ^~~~~~~~~~
In file included from /mnt/files/repos/daos/build/external/release/spdk/include/spdk/stdinc.h:59,
                 from iscsi.c:35:
/usr/include/stdlib.h:538:19: note: previous declaration of 'arc4random' with type '__uint32_t(void)' {aka 'unsigned int(void)'}
  538 | extern __uint32_t arc4random (void)
      |                   ^~~~~~~~~~
make[2]: *** [/mnt/files/repos/daos/build/external/release/spdk/mk/spdk.common.mk:465: iscsi.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  LIB libspdk_nvmf.a
  SO libspdk_nvmf.so.11.0
  SYMLINK libspdk_nvmf.so
make[1]: *** [/mnt/files/repos/daos/build/external/release/spdk/mk/spdk.subdirs.mk:44: iscsi] Error 2
make: *** [/mnt/files/repos/daos/build/external/release/spdk/mk/spdk.subdirs.mk:44: lib] Error 2
BuildFailure: spdk failed to build:
  File "/mnt/files/repos/daos/SConstruct", line 434:
    scons()
  File "/mnt/files/repos/daos/SConstruct", line 357:
    prereqs.load_defaults(platform_arm)
  File "/mnt/files/repos/daos/site_scons/prereq_tools/base.py", line 1106:
    self.load_definitions(prebuild=reqs)
  File "/mnt/files/repos/daos/site_scons/prereq_tools/base.py", line 1082:
    self.require(env, comp)
  File "/mnt/files/repos/daos/site_scons/prereq_tools/base.py", line 1189:
    raise error
  File "/mnt/files/repos/daos/site_scons/prereq_tools/base.py", line 1179:
    if comp_def.build(env, needed_libs):
  File "/mnt/files/repos/daos/site_scons/prereq_tools/base.py", line 1831:
    raise BuildFailure(self.name)
```

`extern __uint32_t arc4random (void)` was added in glibc v2.36: [sourceware.org Git - glibc.git/commit](https://sourceware.org/git/?p=glibc.git;a=commit;h=6f4e0fcfa2d2b0915816a3a3a1d48b4763a7dee2)

## Context

OS: latest Arch Linux with glibc-2.36-6
DAOS: v2.2.0
SPDK: v22.01.1 LTS

**Comment by ldorau** [comment]
```sh
$ echo -e '#include <stdlib.h>\nint main(void) { arc4random(); return 0; }' | gcc  -o /dev/null -x c - ; echo $?
0
```

**Comment by ksztyber** [comment]
Oh, I've just noticed that we've only added these checks in v22.09 via 43a3984c6c8fde7201d6c8dfe1b680cb88237269. We can backport it to v22.01.x, but I'm not sure if we plan to do another v22.01.x release.

**Comment by jimharris** [comment]
> Oh, I've just noticed that we only added these checks in v22.09 via [43a3984](https://github.com/spdk/spdk/commit/43a3984c6c8fde7201d6c8dfe1b680cb88237269). We can backport it to v22.01.x, but I'm not sure if we plan to do another v22.01.x release.

Yeah, let's backport it.  It would be good to have this patch on the v22.01.x branch, even if we don't do another release.

**Comment by KKaras169169** [comment]
The backport to v22.01.x has been merged here: https://review.spdk.io/gerrit/c/spdk/spdk/+/15750 ,so I am closing the issue.
