### ISSUE TITLE
[SPDK with-vpp] failure to build with vpp v20.5

### ISSUE THREAD

**Issue by manjo-git** [spdk/spdk#1440]
## Expected Behavior
SPDK builds with VPP support

## Current Behavior
Failure to build VPP support with VPP version 20.5

The VPP headerfile svm_fifo_segment.h is no longer available in VPP 20.05. But src/module/sock/vpp/vpp.c includes svm/svm_fifo_segment.h this results in the following build failure. 

`
 LIB libspdk_sock_posix.a
  CC module/sock/vpp/vpp.o
vpp.c:52:10: fatal error: svm/svm_fifo_segment.h: No such file or directory
 #include <svm/svm_fifo_segment.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/ubuntu/parts/spdk/build/mk/spdk.common.mk:364: recipe for target 'vpp.o' failed
make[3]: *** [vpp.o] Error 1
/home/ubuntu/parts/spdk/build/mk/spdk.subdirs.mk:44: recipe for target 'vpp' failed
make[2]: *** [vpp] Error 2
/home/ubuntu/parts/spdk/build/mk/spdk.subdirs.mk:44: recipe for target 'sock' failed
make[1]: *** [sock] Error 2
/home/ubuntu/parts/spdk/build/mk/spdk.subdirs.mk:44: recipe for target 'module' failed
make: *** [module] Error 2
Failed to run 'override-build': Exit code was 2.
`

**Comment by tomzawadzki** [comment]
Hi @manjo-git, support for VPP implementation of socket abstraction will be deprecated with SPDK 20.07.
Please see mailing list post for more details - [here](https://lists.01.org/hyperkitty/list/spdk@lists.01.org/message/C7SNVANWUPNIZZ33S5C4KWICSRFW2DQX/).

**Comment by manjo-git** [comment]
@tomzawadzki I was attempting to draw some performance results with NVME-of using SPDK over VPP, and in doing so I ran into these build issues this morning and I was attempting to port/fix the module/sock/vpp/vpp.c to use the latest VPP source changes, but looks like you are right, it has not kept up with the changes in VPP for awhile now. The hardware I am dealing with will only work with VPP v20.05 since it needs support for hugepages and also device PCI IDs etc. and SPDK does not build with this version of VPP. Looks like I am dead in the water.

**Comment by optimistyzy** [comment]
@manjo-git  As described by @tomzawadzki,  SPDK team made decision in mailing list, we will no longer integrate new VPP version.  Thanks.

**Comment by tomzawadzki** [comment]
@manjo-git Is there particular reason why VPP is enticing for you ?
As detailed in the mailing list post - the sockets with Kernel stack got a lot of improvements in recent times. 

Results for this can be seen in recently published [SPDK v20.04 NVMe-oF TCP Performance Report](https://ci.spdk.io/download/performance-reports/SPDK_tcp_perf_report_2004.pdf).
