### ISSUE TITLE
SPDK does not compile on rhel 7.5 after running ./pkgdep.sh

### ISSUE THREAD

**Issue by pcybulski** [spdk/spdk#417]
SPDK didnot compile on rhel 7.5 after running ./pkgdep.sh system was registered with Red Hat and default redhat repositories were added.

## Expected Behavior
Since you support Red Hat it should install all dependencies and compile SPDK without any additional steps necessary.

## Current Behavior
  LINK test/app/stub/stub
  CC test/bdev/bdevio/bdevio.o
bdevio.c:43:25: fatal error: CUnit/Basic.h: No such file or directory
 #include "CUnit/Basic.h"

Also would be nice to have pkgdep.sh display two list at the end:
List of mandatory packages that were not installed and list of optional packages that were not installed if any.

## Possible Solution
CUnit-devel is not available by default in repositories available for people using RHEL Developer Subscription.

In pkgdep.sh script you distinguish between rhel and the rest (CentOS, Fedora) by
        # Includes Fedora, CentOS
        if [ -f /etc/centos-release ]; then
                # Add EPEL repository for CUnit-devel
                yum --enablerepo=extras install -y epel-release
        fi
There should be another check if current os is rhel and then epel repo should be added for it as well.
On https://dl.fedoraproject.org/pub/epel/ there are two rpms listes:
epel-release-latest-6.noarch.rpm 
epel-release-latest-7.noarch.rpm 

So check /etc/redhat-release for "ed Hat Enterprise Linux Server release 6" or "ed Hat Enterprise Linux Server release 7" and install repo with rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-${version}.noarch.rpm 

There is also another option for checking rhel version with lsb_release but it requires installation of additional packages. 

## Steps to Reproduce
1. Install rhel 7.5
2. Subscribe to Red Hat
3. Check available pools by "subscription-manager list --available"
4. Subscribe to chosen pool by "subscription-manager subscribe --pool=${chosen_pool}"
5. git clone https://github.com/spdk/spdk.git
6. cd /root/spdk && git submodule update --init
7.  cd /root/spdk/scripts && ./pkgdep.sh
8. cd /root/spdk && ./configure --enable-debug --with-rdma && make

## Context (Environment including OS version, SPDK version, etc.)
os - Red Hat Enterprise Linux Server release 7.5 (Maipo)
spdk - 58be43c085de23dbcdde2d8d0bf953dc558d3b1a
dpdk - c860b292c96fa11469064add3d5320bcec0fffcf

**Comment by pawelwod** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/424413/ can some one check pls
